### PR TITLE
Added more verbose logging feature

### LINKED ISSUE #12: Make logs more metrics friendly
Should add parse-able metrics to the logs using Splunk formatting as a guide:

http://dev.splunk.com/view/logging/SP-CAAAFCK

### PR DESCRIPTION
**Pull request by nickjer**
Fixes #12 

Requires a modification to the Apache config:

```diff
# Lua configuration
#
LuaRoot "/opt/ood/mod_ood_proxy/lib"
+ LogLevel lua_module:info
+ LuaHookLog logger.lua logger
```

Log looks like...

```
[Fri Feb 09 14:57:26.287584 2018] [lua:info] [pid 1642] [client 131.187.116.55:4286] {"local_user":"jnicklas","log_id":"SkwA8Fwi3y4","remote_user":"f:OSC-LDAP-osc:jnicklas@idp-dev.osc.edu/auth/realms/osc","req_host":"ondemand-dev.osc.edu","req_https":true,"req_method":"GET","req_path":"/pun/sys/dashboard/apps/icon/bc_osc_rstudio_server_bak/dev/jnicklas","req_port":443,"req_referer":"https://ondemand-dev.osc.edu/pun/sys/dashboard/batch_connect/sessions","req_server":"ondemand-dev.osc.edu","req_status":304,"req_websocket":false,"res_disp":"inline; filename=\\"icon.png\\"","res_encoding":"","res_length":"0","res_type":"","time_proxy":59.533,"time_user_map":16.047,"timestamp":"2018-02-09T19:57:26.287396Z","user_accept":"image/webp,image/apng,image/*,*/*;q=0.8","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36","user_encoding":"gzip, deflate, br","user_ip":"131.187.116.55","user_lang":"en-us,en;q=0.9"}, referer: https://ondemand-dev.osc.edu/pun/sys/dashboard/batch_connect/sessions
```

Note: Either Apache or mod_lua is making `\` into `\\`, but as you can see below it can be fixed in the Splunk query command.

It is parsed in Splunk with:

```
sourcetype="apache:error" host=webdev02 error_message="{\"*" | rex field=error_message "(?<msg>{.*})" | rex field=msg mode=sed "s/(\\\){2}/\1/g" | spath input=msg
```

### CODE REVIEW

**Comment by ericfranz** [comment]
Discussed offline. Exploring adding response headers to be consumed by this code from PUN and apps are interesting. Something like a custom header for each whose value is JSON that the lua can attempt to parse, and if valid append the key value pairs to the end of the table that it builds for logging.

If we get burned by apps spamming our logs with unwanted data we could restrict apps that could add those values to sys apps.

Also its worth asking @treydock to review too since our team is new to Splunk.

**Review by ericfranz — APPROVED** [review]

**Comment by nickjer** [comment]
@treydock I went with a JSON string as Splunk has built-in capabilities to parse it, as well as, pretty much every computer language has JSON libraries so another center can parse the logs with any tool of their choosing.

I just don't like that Apache escapes the backslash `\`.

**Comment by treydock** [comment]
If the json is embedded in apache logs then the json parser for splunk won't work the normal way.  If the logs go to somewhere dedicated, outside apache, then we can ingest with sourcetype set as one the builtin json parsers.

It maybe that splunk can handle json embedded in apache logs, just not something I've tested.  I'd have to see logs in action to get a better idea if field extraction in splunk will work.

**Comment by ericfranz** [comment]
@treydock you should see @nickjer demo the extraction to you to verify if that is a good approach or if there is a better way.

**Comment by nickjer** [comment]
I can definitely experiment with a more "field extraction"-friendly method for Splunk. Whatever solution we come up with though needs to solve:

- works with values that contain: spaces, quotes, equal signs, and possibly a slew of other unicode characters
- be parse-able by other languages as we can't expect our Open OnDemand partners to install Splunk
- be flexible - easy to add more key-value pairs in the future
- ideally avoid backslashes as Apache seems to want to escape backslashes a second time in the logs
- ideally use Apache's built-in logging solution as opposed to rolling our own (e.g., writing to another file that we generate as this could complicate log-rolling)

**Comment by nickjer** [comment]
Updated it with a simpler structure. You can also add a Splunk "Field extractor" for the "search" app as:

image

**Comment by treydock** [comment]
@nickjer Just to add in , doing log rotation is very inexpensive and easy with logrotate.  So if we have to resort to writing our own log files, the rotation I would consider a non-issue.

**Comment by nickjer** [comment]
Thanks, that is good to know.

**Pull request merged**
