### PR TITLE
[WIP] Add server-side analytics

### PR DESCRIPTION
**Pull request by nickjer**
Utilizes Google Analytics.

### CODE REVIEW

**Comment by nickjer** [comment]
@ericfranz, any suggestions on metrics you would like (keep in mind this is handled by the proxy and not the back-end PUN).

**Comment by ericfranz** [comment]
One idea, most of our apps that submit jobs have a `/submit` in them. We could filter out requests that include `submit` in the URL and have a response of `200` (is it 200 or 302) and specify that as a "job submission".

It wouldn't be 100% accurate, but it might give an estimate of the number of simulations actually submitted from an app. Though some simulations often will result in multiple jobs getting submitted...

**Comment by ericfranz** [comment]
@basilgohar @nickjer thoughts on making this completed prior to installing OOD at another center? This might make this a priority for this week/next week.

**Comment by nickjer** [comment]
@ericfranz: you can filter the google analytics data for paths that end with `/submit` and are POST requests

**Comment by basilgohar** [comment]
@ericfranz How would checking for /submit work if the app is written by someone else?  Are you proposing we make that a standard protocol for apps?

**Comment by nickjer** [comment]
Pulling this in as it maintains backwards compatibility just fine.

**Pull request merged**
